@CityServiceAPI_HostAddress = http://localhost:5065

### Tüm Sorunları Getir (GET İstediği)
GET {{CityServiceAPI_HostAddress}}/api/issues
Accept: application/json

### Yeni Bir Sorun Ekle (POST İstediği)
POST {{CityServiceAPI_HostAddress}}/api/issues
Content-Type: application/json

{
  "citizenId": 1,
  "categoryId": 1,
  "title": "Park aydınlatması çalışmıyor",
  "description": "Gece saatlerinde park tamamen karanlık kalıyor, çocuklar için güvenlik riski oluşturuyor.",
  "locationData": "Özgürlük Mahallesi, Fatih Caddesi, Çayırova"
}

### Sorunu Personele Ata (POST İstediği) - KİLİT AÇIK
# 2 numaralı sorunu, 2 numaralı personele atıyoruz
POST {{CityServiceAPI_HostAddress}}/api/issues/2/assign/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxMDAyIiwiZW1haWwiOiJheXNlLmtheWFAYmVsZWRpeWUuZ292LnRyIiwicm9sZSI6IlN0YWZmIiwibmJmIjoxNzgzNTgyNTE1LCJleHAiOjE3ODM1ODYxMTUsImlhdCI6MTc4MzU4MjUxNSwiaXNzIjoiQ2l0eVNlcnZpY2VBUEkiLCJhdWQiOiJDaXR5U2VydmljZUNsaWVudHMifQ.qyoOCquvNMEXUh8JFjrWWmnfpL2j3-FrddQB0yxUxgQ

### Bir Sorunu Sil (DELETE İsteği)
# 1 numaralı sorunu (Yolda büyük bir çukur var) sistemden siliyoruz.
DELETE {{CityServiceAPI_HostAddress}}/api/issues/1

### Tüm Kategorileri Getir (GET İstediği)
GET {{CityServiceAPI_HostAddress}}/api/categories
Accept: application/json

### Tüm Kullanıcıları Getir (GET İstediği)
GET {{CityServiceAPI_HostAddress}}/api/users
Accept: application/json

### Sisteme Yeni Bir Personel Ekle (POST İstediği)
POST {{CityServiceAPI_HostAddress}}/api/users
Content-Type: application/json

{
  "firstName": "Ayşe",
  "lastName": "Kaya",
  "email": "ayse.kaya@belediye.gov.tr",
  "passwordHash": "gizlisifre123",
  "role": "Staff"
}

### Bir Soruna Fotoğraf Ekle (POST İstediği)
# 2 numaralı soruna test.jpg dosyasını yüklüyoruz
POST {{CityServiceAPI_HostAddress}}/api/issues/2/upload-image
Content-Type: multipart/form-data; boundary=----MyGreatBoundary

------MyGreatBoundary
Content-Disposition: form-data; name="file"; filename="test.jpg"
Content-Type: image/jpeg

< ./test.jpg
------MyGreatBoundary--

### Sisteme Giriş Yap ve Token Al (POST)
# Daha önce eklediğimiz "Ayşe Kaya" (Staff) kullanıcısının bilgileriyle giriş yapıyoruz
POST {{CityServiceAPI_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "ayse.kaya@belediye.gov.tr",
  "password": "gizlisifre123"
}