// <auto-generated />
using System;
using CityServiceAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityServiceAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260716140852_SeedCategories")]
    partial class SeedCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CityServiceAPI.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("IssueId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("StaffNotes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Assignme__3214EC077CDB8CEB");

                    b.HasIndex("IssueId");

                    b.HasIndex("StaffId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("CityServiceAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ExpectedResolutionHours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC0781C6ED88");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentName = "Fen İşleri",
                            ExpectedResolutionHours = 48,
                            Name = "Altyapı (Pothole vb.)"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentName = "Park ve Bahçeler",
                            ExpectedResolutionHours = 24,
                            Name = "Park ve Bahçeler"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentName = "Temizlik İşleri",
                            ExpectedResolutionHours = 12,
                            Name = "Temizlik"
                        });
                });

            modelBuilder.Entity("CityServiceAPI.Models.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GpsLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LocationData")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ReportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK__Issues__3214EC0755719DE8");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CitizenId");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("CityServiceAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07ACB80466");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534A06D0A59")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CityServiceAPI.Models.Assignment", b =>
                {
                    b.HasOne("CityServiceAPI.Models.Issue", "Issue")
                        .WithMany("Assignments")
                        .HasForeignKey("IssueId")
                        .IsRequired()
                        .HasConstraintName("FK__Assignmen__Issue__30F848ED");

                    b.HasOne("CityServiceAPI.Models.User", "Staff")
                        .WithMany("Assignments")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK__Assignmen__Staff__31EC6D26");

                    b.Navigation("Issue");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("CityServiceAPI.Models.Issue", b =>
                {
                    b.HasOne("CityServiceAPI.Models.Category", "Category")
                        .WithMany("Issues")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Issues__Category__2D27B809");

                    b.HasOne("CityServiceAPI.Models.User", "Citizen")
                        .WithMany("Issues")
                        .HasForeignKey("CitizenId")
                        .IsRequired()
                        .HasConstraintName("FK__Issues__CitizenI__2C3393D0");

                    b.Navigation("Category");

                    b.Navigation("Citizen");
                });

            modelBuilder.Entity("CityServiceAPI.Models.Category", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("CityServiceAPI.Models.Issue", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("CityServiceAPI.Models.User", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
